server:
  port: 80
  tomcat:
    uri-encoding: UTF-8


spring:
  datasource:
    url: jdbc:mysql://rm-bp1e5v7r58se890h4go.mysql.rds.aliyuncs.com:3306/gxutrainbranch?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong
    username: maomao
    password: MaoMao114514
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #初始状态数量
      initial-size: 5
      #最小连接数
      min-idle: 5
      #最大连接数
      max-active: 20
      #毫秒
      max-wait: 60000
mybatis:
  mapper-locations: classpath:mapper/*.xml

jwt:
  secret: MaoMAO
  expiration: 3000
